In [1]:
import numpy as np

In [2]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
arr[5]


np.int64(6)

In [4]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [5]:
arr[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
arr[3:10:2]

array([ 4,  6,  8, 10])

In [8]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [12]:
arr[0,5]

np.int64(6)

In [13]:
arr[2,5]

np.int64(18)

In [17]:
slice=arr[0:4,3:5]
slice

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])

In [18]:
arr[:,2]

array([ 3,  9, 15, 21, 27])