In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a=[1,2,3]
a

[1, 2, 3]

In [5]:
b=[2,3,4.5,"hello"]
b

[2, 3, 4.5, 'hello']

In [6]:
np.array(b)


array(['2', '3', '4.5', 'hello'], dtype='<U32')

In [8]:
c=[[1,2,3],[4,5,6]]
c

[[1, 2, 3], [4, 5, 6]]

In [9]:
np.array(c)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
aa=np.linspace(1,3,50)
aa

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [15]:
arr=np.random.rand(10)
arr

array([0.10541554, 0.85845587, 0.79406055, 0.74989372, 0.59914329,
       0.50491185, 0.50583593, 0.73955032, 0.72624648, 0.03058542])

In [16]:
arr=np.random.randn(10)
arr

array([ 1.98486951, -0.21433869, -0.58054395, -1.33752328, -1.22196137,
        1.09430982,  0.12265462, -0.61693578, -0.37610215, -1.20045658])

In [17]:
arr=np.random.randint(5)
arr

2

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [28]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.argmax()

np.int64(8)

In [31]:
arr.argmin()

np.int64(0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [33]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr=arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])