In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [3]:
a1-a2

array([-5, -5, -5, -5, -5])

In [4]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [7]:
c=[5,15,25]
arr=np.array(c)

In [8]:
arr+5

array([10, 20, 30])

In [1]:
import numpy as np

In [3]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [6]:
# SHALLOW COPY

In [8]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a=arr[:6]
a*100

array([100, 200, 300, 400, 500, 600])

In [23]:
A = np.array([[1,2],[3,4]])
C = np.array([[5,6],[7,8]])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
C

array([[5, 6],
       [7, 8]])

In [26]:
 A@C        # OR WE CAN USE np.dot(A,C)  AND THIS IS USE FOR MATRIX MULTIPLICATION

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(A,C)

array([[19, 22],
       [43, 50]])

In [28]:
A.T       # TRANSPOSE

array([[1, 3],
       [2, 4]])

In [29]:
#  STACKING ARRAY

In [31]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [34]:
arr=np.vstack((a,b))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
arr=np.hstack((a,b))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr=np.column_stack((a,b))
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
arr=np.row_stack((a,b))
arr

C:\Users\chinm\AppData\Local\Temp\ipykernel_5180\2393044248.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr=np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])