In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [34]:
r=np.array([1,2,3,4])
r

array([1, 2, 3, 4])

In [1]:
import numpy as np

In [2]:
#  VALID SUDOKO 

In [40]:
arr=np.array([[5,3,4,6,7,8,9,1,2],
              [6,7,2,1,9,5,3,4,8],
              [1,9,8,3,4,2,5,6,7],
              [8,5,9,7,6,1,4,2,3],
              [4,2,6,8,5,3,7,9,1],
              [7,1,3,9,2,4,8,5,6],
              [9,6,1,5,3,7,2,8,4],
              [2,8,7,4,1,9,6,3,5],
              [3,4,5,2,8,6,1,7,9]])


In [41]:
c=np.sum(arr,axis=1)
c[c==45]


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [42]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [43]:
for i in c:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:
        print("Valid Sudoku for rows")    


Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows
Valid Sudoku for rows


In [44]:
d=np.sum(arr,axis=0)

for i in c:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:
        print("Valid Sudoku for coulmns")  


Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns
Valid Sudoku for coulmns


In [45]:
h=arr[0:3,0:3]
h.sum()

np.int64(45)

In [47]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(arr[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [48]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(arr[i:i+3,j:j+3].sum())

45
45
45
45
45
45
45
45
45


In [17]:
# columns=[age,maths marks, science marks]
import numpy as np
data=np.array([[18,85,78],
               [19,95,80],
               [20,80,90],
               [21,90,85]])


In [18]:
#  SHAPE OF MATRIX
data.shape


(4, 3)

In [19]:
# Mean of age column 
f=data[:,:1]
f.mean()


np.float64(19.5)

In [20]:
# Extract marks of maths
g=data[:,1:2]
g


array([[85],
       [95],
       [80],
       [90]])

In [21]:
#  highest marks in science
h=max(data[:,2:3])
h

array([90])

In [22]:
# student got marks greater than 90 in maths 
data[data[:,1]>90]

array([[19, 95, 80]])

In [23]:
#  INCREASE MATHS MARKS OF ALL STUDENTS BY 5
data[:,1]+=5
data


array([[ 18,  90,  78],
       [ 19, 100,  80],
       [ 20,  85,  90],
       [ 21,  95,  85]])

In [25]:
#  STUDENTS YOUNGER THAN 19
len(data[data[:,0]<19])

1

In [26]:
#  CALCULATE AVERAGE OF EACH SUBJECT
np.mean(data[:,1:],axis=0)

array([92.5 , 83.25])

In [28]:
#  GET DATA OF STUDENTS WHO SCORE ATLEAST 80 IN BOTH SUBJECTS
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[ 19, 100,  80],
       [ 20,  85,  90],
       [ 21,  95,  85]])

In [29]:
data

array([[ 18,  90,  78],
       [ 19, 100,  80],
       [ 20,  85,  90],
       [ 21,  95,  85]])